// Copyright (c) [Year] [name of copyright holder]
// Open-Plugin is licensed under Mulan PSL v2.
// You can use this software according to the terms and conditions of the Mulan
// PSL v2.
// You may obtain a copy of Mulan PSL v2 at:
//          http://license.coscl.org.cn/MulanPSL2
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
// KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
// See the Mulan PSL v2 for more details.

#pragma once
#include "event_helper.hxx"

#define MACH_MQTT_EVT_LIST                                                     \
  (INFO_REPORT, NETWORK_QUERYINFO, AUTOOPERATION_SET, AUTOOPERATION_GET,       \
   AUTOOPERATION_REPORTSTATUS, REPORTAUTOFEEDINFO, FEEDRESIN,                  \
   SMARTRESINVAT_CYCLICCLEANING, SMARTRESINVAT_REPORTINFO, RELEASEFILM_GET,    \
   RELEASEFILM_RESET, AIRPURE_OFF, AIRPURE_ON, OTA_REPORT_VERSION, OTA_UPDATE, \
   OTA_UPDATE_SUCCESS, OTA_UPDATE_FAIL, OTA_UPDATE_START,                      \
   OTA_UPDATE_DOWNLOADING, OTA_UPDATE_UPDATING, OTA_CANCELED_CANCELED,         \
   OTA_UPDATE_DOWNLOADING_FAILED, ONLINE_REPORT, RESIDUAL_CLEAN,               \
   RESIDUAL_CANCEL, AXIS_MOVE, AXIS_QUERY, AXIS_TURNOFF,                       \
   AXIS_MOVETOCOORDINATES, EXPOSURE_CHECK_START, EXPOSURE_CANCEL, WIFI_SIGNAL, \
   PRINTER_STATUS_FREE, PRINTER_STATUS_BUSY, PRINTER_STATUS_REPORT,            \
   TEMPATURE_STATUS_AUTO, FILE_LIST_UDISK, FILE_LIST_LOCAL, FILE_DELETE_UDISK, \
   FILE_DELETE_LOCAL, PRINT_RESUME, PRINT_STOP, PRINT_PAUSE, PRINT_START,      \
   PRINT_UPDATE, PRINT_IGNORE, PRINT_MONITOR, PRINT_QUERY,                     \
   PRINT_AUTOOPERATION, PRINT_REDETECT, VIDEO_STREAM_START, VIDEO_STREAM_STOP, \
   FILAMENT_REPLACE, FILAMENT_SET, ZOFF_MOVE, MCB_GET_INFO, MCB_SET_DRY,       \
   MCB_AUTO_UPDATE_DRY_STATUS, MCB_FEED_FILAMENT, MCB_FINISH_FEED_FILAMENT,    \
   MCB_SET_AUTO_FEED, MCB_REFRESH, MCB_SET_INFO, MCB_AUTO_UPDATE_INFO)

#define MACH_MQTT_EVT_LIST_2                                                   \
  (LIGHT_CONTRL, EFB_REPORT_INFO, PERIPHERIE_QUERY, CONNECT, DISCONNECT,       \
   SUBSCRIBE, UNSUBCRIBE, CONNECT_LOST, PUBLISH, NEW_CLIENT, REMOVE_CLIENT)

EVENT_HELPER_DECLARE(impl_wxDECLARE_EVENT, WXEVT_MACH_MQTT_, MACH_MQTT_EVT_LIST)
EVENT_HELPER_DECLARE(impl_wxDECLARE_EVENT, WXEVT_MACH_MQTT_,
                     MACH_MQTT_EVT_LIST_2)