// Copyright (c) [Year] [name of copyright holder]
// Open-Plugin is licensed under Mulan PSL v2.
// You can use this software according to the terms and conditions of the Mulan
// PSL v2.
// You may obtain a copy of Mulan PSL v2 at:
//          http://license.coscl.org.cn/MulanPSL2
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
// KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
// See the Mulan PSL v2 for more details.

#include "plugin_custom_event.hxx"

wxDEFINE_EVENT(EVT_GET_NOW_FILAMENT_LIST_INFO, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_FRAMGROUP_REMOTE, wxPluginEvent); // 农场发送任务
wxDEFINE_EVENT(EVT_ACCLOUD_PRINTER_REMOTE, wxPluginEvent);   // 远程打印

wxDEFINE_EVENT(EVT_REMOTE_AMS_CHANGE, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_AMS_CHANGE_SEND, wxPluginEvent);

wxDEFINE_EVENT(EVT_PRINTER_GET_BOX_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_WEBWAKE_DOWN_PAR, wxPluginEvent);
wxDEFINE_EVENT(EVT_WEBWAKE_DOWN_PAR_INDEX, wxPluginEvent);
wxDEFINE_EVENT(EVT_PRINTER_DELETE_LAN, wxPluginEvent);
wxDEFINE_EVENT(EVT_PRINTER_PRINT_FINISH, wxPluginEvent);
wxDEFINE_EVENT(EVT_SLICING_AUTO_EXPORT_GCODE3MF, wxPluginEvent);
wxDEFINE_EVENT(EVT_ZIP_FILE_FINISH_EVENT, wxPluginEvent);

wxDEFINE_EVENT(EVT_AUTO_FILE_OPEN_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_AUTO_FILE_OPEN_FINISH_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_AUTO_SLICER_FINISH_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_AUTO_REMOTEPRINTSHOW_FINISH_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_AUTO_SLOOP_FINISH_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_AUTO_SLICER_FAIL_EVENT, wxPluginEvent);

wxDEFINE_EVENT(EVT_FRAM_CRATE_TASK_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_GET_CLOUD_SLICER_INFO_FINISH_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_GET_CLOUD_SLICER_INFO_ERR_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_CLOUD_FILE_START_PRINT_EVENT, wxPluginEvent);

wxDEFINE_EVENT(EVT_DOWN_MODEL_IMG_FINISH_EVENT, wxPluginEvent);

wxDEFINE_EVENT(EVT_FRAM_GET_PRINTER_LIST_EVENT, wxPluginEvent);

wxDEFINE_EVENT(EVT_AMS_SHOW_CHANGE_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_AMS_SHOW_CHANGE_MORE_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_AMS_SHOW_GUI_CHANGE_EVENT, wxPluginEvent);

wxDEFINE_EVENT(EVT_POP_DELETE_EVENT, wxPluginEvent);

wxDEFINE_EVENT(EVT_ACCLOUD_PRINTER_STATE, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_INFO_RELEPACE_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_CANCEL_ACCOULD_UPLOAD_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_MODEL_LOGIN_DIALOG_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACTION_LOGOUT_COMPEL, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACTION_OPTIONS, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACTION_OPTIONS_FINISH, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_LOGIN_IN, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_PRINTERLIST, wxPluginEvent);

wxDEFINE_EVENT(EVT_ACTION_UPLOAD, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACTION_REMOTEPRINTER, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_PRINTER_ADD, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_PRINTER_RENAME, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_PRINTER_DELETE, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_PRINTER_AMS, wxPluginEvent);
wxDEFINE_EVENT(EVT_CANCEL_ACCOULD_UPLOAD_GCODEUP_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_PRINTER_PERIPHERIE, wxPluginEvent);

wxDEFINE_EVENT(EVT_AMS_INFO_CHANGE_EVENT, wxPluginEvent);

/*
               ========== LAN INFO ==============
*/

wxDEFINE_EVENT(EVT_LAN_CONNECT_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_LAN_CANCLE_UPLOAD_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_LAN_GETMULTI_COLOR_BOX_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_LAN_QUERY_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_LAN_REMOTE_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_LAN_GET_PRINTERS_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_LAN_DEVICESAVE_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_LAN_PRINTER_LAN_STATE_CHANGE_EVENT, wxPluginEvent);

/*
               ========== LAN INFO ==============
*/

/*
               ========== SendPrint INFO ==============
*/

wxDEFINE_EVENT(EVT_SLICER_ALL_IFNO_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_SEND_FILE_FINISH_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_SEND_LAN_UPLOAD_FILES_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_SEND_FILES_GUI_RESULT_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_SUB_SEND_FINISH, wxPluginEvent);
wxDEFINE_EVENT(EVT_START_SEND_FILE_LAN_PRINTER_EVENT, wxPluginEvent);

/*
               ========== SendPrint INFO ==============
*/

/*
               ========== Farm INFO ==============
*/

wxDEFINE_EVENT(EVT_FARM_GROUP_SELECT_PRINTER_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_FARM_GROUP_SELECT_PRINTER_FINISH_EVENT, wxPluginEvent);

wxDEFINE_EVENT(EVT_FARM_GROUP_CHANGE_AMS_SLOT_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_FARM_GROUP_AUTO_OP_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_FARM_GROUPLIST_GET_CLOUD_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_FARM_GROUPLIST_GET_CLOUD_TO_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_FARM_GROUPLIST_SELECT_ALL_EVENT, wxPluginEvent);

/*
               ========== Farm INFO ==============
*/

/*
               ========== Remoteing INFO ==============
*/

wxDEFINE_EVENT(EVT_REMOTE_PRINTER_OP_CANCEL, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_SEND_ERRFINISH, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_SEND_FINISH, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_UPLOAD_PROGRESS_ERR, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_UPLOAD_PROGRESS, wxPluginEvent);

wxDEFINE_EVENT(EVT_REMOTE_PRINTER_AMS_CHANGE, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_INFO, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_AMS_INFO, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_CHANGE, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_FUNCTION_RESULT, wxPluginEvent);

wxDEFINE_EVENT(EVT_REMOTE_PRINTER_LOGINSTATE_CHANGE, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_LOGINSTATE_CLOSETIME, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_LOGINSTATE_TIMESTATR, wxPluginEvent);

wxDEFINE_EVENT(EVT_REMOTE_PRINTER_LAN_UPLOAD_GCODE, wxPluginEvent);

wxDEFINE_EVENT(EVT_REMOTE_PRINTER_LAN_MQTT_FINISH, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_LAN_SUBSCRIBE_FINISH, wxPluginEvent);

wxDEFINE_EVENT(EVT_REMOTE_PRINTER_LAN_RESET, wxPluginEvent);

wxDEFINE_EVENT(EVT_REMOTE_PRINTER_CHANGE_NEW, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_CHANGE_NEW_LAN, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_AMS_CHANGE_NEW, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_FUNCITION_CHANGE_NEW, wxPluginEvent);

wxDEFINE_EVENT(EVT_REMOTE_OP_AMS_CHANGE_INFO_MANGER, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_OP_AMS_CHANGE_INFO, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_OP_DRYING_INFO, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_OP_SEND_ERR, wxPluginEvent);
wxDEFINE_EVENT(EVT_REMOTE_PRINTER_OP_SEND_ERR_MANAGE, wxPluginEvent);

/*

               ========== Remoteing INFO ==============
*/

/*
               ========== AUto INFO ==============
*/

wxDEFINE_EVENT(EVT_AUTO_CLICK_EVENT, wxPluginEvent);
/*
               ========== AUto INFO ==============
*/

wxDEFINE_EVENT(EVT_AMS_POP_DISMISS, wxPluginEvent);
wxDEFINE_EVENT(EVT_AMS_POP_SELECT, wxPluginEvent);

wxDEFINE_EVENT(EVT_SELECT_SHOW_EVENT, wxPluginEvent);

/*
                ========== Upload INFO ==============
*/

wxDEFINE_EVENT(EVT_ACCLOUD_FILE_UPLOAD_PROGRESS, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_FILE_UPLOAD_ERROR, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_FILE_UPLOAD_NET_ERROR, wxPluginEvent);
wxDEFINE_EVENT(EVT_ACCLOUD_FILE_UPLOAD_CLOUD_PROGRESS, wxPluginEvent);

/*
                ========== Upload INFO ==============
*/

/*
                ========== postevent INFO ==============
*/

wxDEFINE_EVENT(EVT_POST_LAST_VERSION_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_POST_DOWN_PAR_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_POST_GET_LAST_VERSION_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_POST_SHOW_NEW_VERSIONPAR_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_POST_MOPAGE_VIEW_EVENT, wxPluginEvent);
wxDEFINE_EVENT(EVT_POST_MOMODEL_DOWN_CLICK_EVENT, wxPluginEvent);

/*
                ========== postevent INFO ==============
*/

wxDEFINE_EVENT(EVT_DIALOG_CLOSE_EVENT, wxCommandEvent);

wxDEFINE_EVENT(EVT_CHANGE_CODE_BTN, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHANGE_OPEN_WEB, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHANGE_RESET_PASS_EVENT, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHANGE_SET_ERR_EVENT, wxCommandEvent);

wxDEFINE_EVENT(EVT_CHANGE_LOGIN_RESULT_EVENT, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHANGE_CHICK_RESULT_EVENT, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHANGE_CAPTCHA_RESULT_EVENT, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHANGE_RESETPASS_RESULT_EVENT, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHANGE_REGISTER_RESULT_EVENT, wxCommandEvent);

wxDEFINE_EVENT(EVT_SELECT_TAB, wxCommandEvent);
wxDEFINE_EVENT(EVT_HTTP_ERROR, wxCommandEvent);
wxDEFINE_EVENT(EVT_USER_LOGIN, wxCommandEvent);
wxDEFINE_EVENT(EVT_USER_LOGIN_HANDLE, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHECK_PRIVACY_VER, wxCommandEvent);
wxDEFINE_EVENT(EVT_CHECK_PRIVACY_SHOW, wxCommandEvent);
wxDEFINE_EVENT(EVT_SHOW_IP_DIALOG, wxCommandEvent);
wxDEFINE_EVENT(EVT_SET_SELECTED_MACHINE, wxCommandEvent);
wxDEFINE_EVENT(EVT_UPDATE_MACHINE_LIST, wxCommandEvent);

wxDEFINE_EVENT(EVT_BACKUP_POST, wxCommandEvent);
wxDEFINE_EVENT(EVT_LOAD_URL, wxCommandEvent);

wxDEFINE_EVENT(EVT_SHOW_DIALOG_WARNING, wxCommandEvent);

wxDEFINE_EVENT(EVT_REPORT_USERLOGININFO_EVENT, wxCommandEvent);
wxDEFINE_EVENT(EVT_REPORT_USERREGEDITINFO_EVENT, wxCommandEvent);
wxDEFINE_EVENT(EVT_EN_LOGIN_CLOSE_EVENT, wxCommandEvent);

wxDEFINE_EVENT(EVT_OPEN_PREFERENCES_EVENT, wxCommandEvent);
wxDEFINE_EVENT(EVT_HOME_PAGE_RELOAD, wxCommandEvent);
wxDEFINE_EVENT(EVT_SENSORS_SEND_EVENT, wxCommandEvent);

wxDEFINE_EVENT(EVT_P_CLOSE_CAPTCHA_EVENT, wxCommandEvent);