#pragma once

#include <wx/event.h>
#include <wx/wx.h>
#include "../plugin_event.hxx"

using wxPluginEvent = Anycubic::Plugins::SDK::wxPluginEvent;
wxDECLARE_EVENT(EVT_GET_NOW_FILAMENT_LIST_INFO, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_FRAMGROUP_REMOTE, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_PRINTER_REMOTE, wxPluginEvent); 
wxDECLARE_EVENT(EVT_REMOTE_AMS_CHANGE, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_AMS_CHANGE_SEND, wxPluginEvent);
wxDECLARE_EVENT(EVT_PRINTER_GET_BOX_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_WEBWAKE_DOWN_PAR, wxPluginEvent);
wxDECLARE_EVENT(EVT_WEBWAKE_DOWN_PAR_INDEX, wxPluginEvent);
wxDECLARE_EVENT(EVT_PRINTER_DELETE_LAN, wxPluginEvent);
wxDECLARE_EVENT(EVT_PRINTER_PRINT_FINISH, wxPluginEvent);
wxDECLARE_EVENT(EVT_SLICING_AUTO_EXPORT_GCODE3MF, wxPluginEvent);
wxDECLARE_EVENT(EVT_ZIP_FILE_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AUTO_FILE_OPEN_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AUTO_FILE_OPEN_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AUTO_SLICER_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AUTO_REMOTEPRINTSHOW_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AUTO_SLOOP_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AUTO_SLICER_FAIL_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_DOWN_MODEL_IMG_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_GET_CLOUD_SLICER_INFO_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_GET_CLOUD_SLICER_INFO_ERR_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_CLOUD_FILE_START_PRINT_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_FRAM_CRATE_TASK_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_FRAM_GET_PRINTER_LIST_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AMS_SHOW_CHANGE_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AMS_SHOW_CHANGE_MORE_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_AMS_SHOW_GUI_CHANGE_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_POP_DELETE_EVENT, wxPluginEvent);

wxDECLARE_EVENT(EVT_ACCLOUD_PRINTER_STATE, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_INFO_RELEPACE_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_CANCEL_ACCOULD_UPLOAD_EVENT, wxPluginEvent); 
wxDECLARE_EVENT(EVT_MODEL_LOGIN_DIALOG_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACTION_LOGOUT_COMPEL, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACTION_OPTIONS, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACTION_OPTIONS_FINISH, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_LOGIN_IN, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_PRINTERLIST, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACTION_UPLOAD, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACTION_REMOTEPRINTER, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_PRINTER_ADD, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_PRINTER_RENAME, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_PRINTER_DELETE, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_PRINTER_AMS, wxPluginEvent);
wxDECLARE_EVENT(EVT_CANCEL_ACCOULD_UPLOAD_GCODEUP_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_PRINTER_PERIPHERIE, wxPluginEvent);


wxDECLARE_EVENT(EVT_AMS_INFO_CHANGE_EVENT, wxPluginEvent);




/*
                ========== LAN INFO ==============
*/

wxDECLARE_EVENT(EVT_LAN_CONNECT_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_LAN_CANCLE_UPLOAD_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_LAN_GETMULTI_COLOR_BOX_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_LAN_QUERY_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_LAN_REMOTE_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_LAN_GET_PRINTERS_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_LAN_DEVICESAVE_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_LAN_PRINTER_LAN_STATE_CHANGE_EVENT, wxPluginEvent);
/*
                ========== LAN INFO ==============
*/

/*
                ========== SendPrint INFO ==============
*/

wxDECLARE_EVENT(EVT_SLICER_ALL_IFNO_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_SEND_FILE_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_SEND_LAN_UPLOAD_FILES_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_SEND_FILES_GUI_RESULT_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_SUB_SEND_FINISH, wxPluginEvent);
wxDECLARE_EVENT(EVT_START_SEND_FILE_LAN_PRINTER_EVENT, wxPluginEvent);
/*
                ========== SendPrint INFO ==============
*/

/*
                ========== Farm INFO ==============
*/

wxDECLARE_EVENT(EVT_FARM_GROUP_SELECT_PRINTER_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_FARM_GROUP_SELECT_PRINTER_FINISH_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_FARM_GROUP_CHANGE_AMS_SLOT_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_FARM_GROUP_AUTO_OP_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_FARM_GROUPLIST_GET_CLOUD_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_FARM_GROUPLIST_GET_CLOUD_TO_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_FARM_GROUPLIST_SELECT_ALL_EVENT, wxPluginEvent);

/*
                ========== Farm INFO ==============
*/

/*
                ========== Remoteing INFO ==============
*/

wxDECLARE_EVENT(EVT_REMOTE_PRINTER_OP_CANCEL, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_UPLOAD_PROGRESS_ERR, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_SEND_ERRFINISH, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_SEND_FINISH, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_UPLOAD_PROGRESS, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_AMS_CHANGE, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_INFO, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_AMS_INFO, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_CHANGE, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_FUNCTION_RESULT, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_LOGINSTATE_CHANGE, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_LOGINSTATE_CLOSETIME, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_LOGINSTATE_TIMESTATR, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_LAN_UPLOAD_GCODE, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_LAN_MQTT_FINISH, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_LAN_SUBSCRIBE_FINISH, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_LAN_RESET, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_CHANGE_NEW, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_CHANGE_NEW_LAN, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_AMS_CHANGE_NEW, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_FUNCITION_CHANGE_NEW, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_OP_AMS_CHANGE_INFO_MANGER, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_OP_AMS_CHANGE_INFO, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_OP_DRYING_INFO, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_OP_SEND_ERR, wxPluginEvent);
wxDECLARE_EVENT(EVT_REMOTE_PRINTER_OP_SEND_ERR_MANAGE, wxPluginEvent);

/*
                ========== Remoteing INFO ==============
*/

/*
                ========== AUto INFO ==============
*/

wxDECLARE_EVENT(EVT_AUTO_CLICK_EVENT, wxPluginEvent);
/*
                ========== AUto INFO ==============
*/

wxDECLARE_EVENT(EVT_AMS_POP_DISMISS, wxPluginEvent);
wxDECLARE_EVENT(EVT_AMS_POP_SELECT, wxPluginEvent);
wxDECLARE_EVENT(EVT_SELECT_SHOW_EVENT, wxPluginEvent);




/*
                ========== Upload INFO ==============
*/


wxDECLARE_EVENT(EVT_ACCLOUD_FILE_UPLOAD_PROGRESS, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_FILE_UPLOAD_ERROR, wxPluginEvent);
wxDECLARE_EVENT(EVT_ACCLOUD_FILE_UPLOAD_NET_ERROR, wxPluginEvent);

wxDECLARE_EVENT(EVT_ACCLOUD_FILE_UPLOAD_CLOUD_PROGRESS, wxPluginEvent);


/*
                ========== Upload INFO ==============
*/


/*
                ========== postevent INFO ==============
*/

wxDECLARE_EVENT(EVT_POST_LAST_VERSION_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_POST_DOWN_PAR_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_POST_GET_LAST_VERSION_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_POST_SHOW_NEW_VERSIONPAR_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_POST_MOPAGE_VIEW_EVENT, wxPluginEvent);
wxDECLARE_EVENT(EVT_POST_MOMODEL_DOWN_CLICK_EVENT, wxPluginEvent);

/*
                ========== postevent INFO ==============
*/

