# 插桩仅仅是有问题才需要开启，其他情况都不要打开，浪费性能
option(OPENPLUGINS_INSTRUMENT "Enable instrumentation" OFF)
if(OPENPLUGINS_INSTRUMENT AND CMAKE_BUILD_TYPE STREQUAL "Debug")
    function(merge_exclude_paths output_var)
        set(EXCLUDE_PATHS "")
        foreach(item ${ARGN})
            if(item AND IS_ABSOLUTE ${item})
                list(APPEND EXCLUDE_PATHS "${item}/*")  
            elseif(item)
                foreach(PATH ${${item}})
                    list(APPEND EXCLUDE_PATHS "${PATH}/*")  
                endforeach()
            endif()
        endforeach( )
        foreach(PATH ${EXCLUDE_PATHS})
                string(REPLACE "//" "/" PATH ${PATH})
                string(REPLACE "\\/" "/" PATH ${PATH})
                list(APPEND ${output_var} ${PATH})
        endforeach()
        list(REMOVE_DUPLICATES ${output_var})  
        string(JOIN "," ${output_var} ${${output_var}}) 
        set(${output_var} ${${output_var}} PARENT_SCOPE)
    endfunction()

    function(config_instrument target)
        if(NOT TARGET ${target})
            message(FATAL_ERROR "Target ${target} does not exist")
        endif()
        if(CMAKE_HOST_WIN32)
            target_compile_options(${target} INTERFACE /Gh /GH)
            target_link_libraries(${target} INTERFACE dbghelp psapi)
        else()
            if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
                target_compile_options(${target} INTERFACE -finstrument-functions -fno-omit-frame-pointer)
            else()
                # 针对Apple Clang补充macOS/iOS SDK路径
                if(CMAKE_HOST_APPLE)
                    # 获取Apple SDK路径（自动适配Xcode版本）
                    execute_process(
                        COMMAND xcrun --show-sdk-path
                        OUTPUT_VARIABLE APPLE_SDK_PATH
                        OUTPUT_STRIP_TRAILING_WHITESPACE
                    )
                    if(APPLE_SDK_PATH)
                        list(APPEND SYSTEM_EXCLUDE_PATHS "${APPLE_SDK_PATH}/usr/*")
                    endif()
                    list(APPEND SYSTEM_EXCLUDE_PATHS  "/Library/*" "/Applications/Xcode.app/*")
                endif()
                list(APPEND SYSTEM_EXCLUDE_PATHS "/usr/*" "*/boost/*")
                merge_exclude_paths(SYSTEM_EXCLUDE_PATHS  SYSTEM_EXCLUDE_PATHS CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES CMAKE_PREFIX_PATH CMAKE_SYSTEM_INCLUDE_PATH CMAKE_SYSTEM_LIBRARY_PATH)
                target_compile_options(${target} INTERFACE -finstrument-functions -fno-omit-frame-pointer -finstrument-functions-exclude-file-list=${SYSTEM_EXCLUDE_PATHS})
            endif()
            target_link_libraries(${target} INTERFACE dl)
        endif()
    endfunction()
else()
    function(config_instrument target)
            message("Instrumentation is disabled for ${target}")
    endfunction()
endif()
